#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/software/nrn_py2"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/software/nrn_py2/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/u/cliffk/okinawa/heidi/project/Lonardoni2017_data/x86_64/.libs/libnrnmech.so" "$@"
